### PR TITLE
Persist column visibility

### PR DESCRIPTION
**Pull request by samdeane**
Hopefully not too controversial!

### CODE REVIEW

**Comment by samdeane** [comment]
(actually, just realised I'm not persisting it here... doh! will amend the PR)

**Comment by schwa** [comment]
Another option is to make the type respond to rawRepresentable (where the raw value is a type that can fit into a propertyList). Might be less code than the Binding adapter?

**Comment by samdeane** [comment]
Yeah, I actually tried that, with an extension to `NavigationSplitViewVisibility` which conformed it to `RawRepresentable` but it didn't seem to want to work.

**Comment by samdeane** [comment]
I might have done something dumb, so could try again - I agree that it ought to work, looking at the interface of SceneStorage/AppStorage. 

I was also thinking that one could probably write a couple of property wrappers that wrap AppStorage and SceneStorage and do the work in them, which would possibly be cleaner still.

**Comment by samdeane** [comment]
You'd think that this ought to work, but...

image

**Comment by schwa** [comment]
Perfect! (Changed base branch to integration)

**Pull request merged**
